
-- Add image_url column
ALTER TABLE public.sales_training_cards ADD COLUMN image_url TEXT;

-- Insert dummy training cards
INSERT INTO public.sales_training_cards (product, role, title, sort_order, image_url, dialogues) VALUES
('HRMS', 'Sales Rep', 'Opening Pitch – First Contact', 1, 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=400&h=250&fit=crop', '[{"question":"Hi, I am calling from TechCorp. Do you have a moment to discuss your HR processes?","answer":"Sure, but make it quick. We are pretty busy."},{"question":"Absolutely! Many companies like yours spend hours on manual attendance and payroll. How do you currently handle that?","answer":"We use spreadsheets mostly. It works but it is a pain."},{"question":"That is exactly why our HRMS exists – it automates attendance, payroll, and leave management in one place. Can I show you a quick demo?","answer":"Okay, that sounds interesting. Send me a link."}]'),
('HRMS', 'Customer', 'Handling Pricing Objections', 2, 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=250&fit=crop', '[{"question":"This looks good but honestly it is out of our budget right now.","answer":"I completely understand. Let me ask – how much time does your HR team spend on payroll each month?"},{"question":"Probably 3-4 full days every month.","answer":"So that is nearly 48 days a year. With our HRMS, that drops to half a day. The time savings alone pay for the subscription. Would you like to see the ROI calculator?"},{"question":"Hmm, when you put it that way... yes, show me the numbers.","answer":"Great! I will walk you through it right now."}]'),
('HRMS', 'Manager', 'Team Onboarding Walkthrough', 3, 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&h=250&fit=crop', '[{"question":"We just signed up. How do we get the whole team on board quickly?","answer":"Great question! First, I will help you set up departments and roles in the admin panel. It takes about 10 minutes."},{"question":"What about employee data – do we have to enter everything manually?","answer":"Not at all. You can bulk upload via CSV. We also have a self-service portal where employees fill in their own details."},{"question":"That saves a lot of work. What about training the HR team?","answer":"We provide a 30-minute live training session plus video guides they can revisit anytime."}]'),
('HRMS', 'Sales Rep', 'Competitor Comparison Call', 4, 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=400&h=250&fit=crop', '[{"question":"We are already evaluating another HRMS tool. Why should we consider yours?","answer":"That is smart to compare. Can I ask which tool you are looking at?"},{"question":"We are considering ZohoHR.","answer":"Solid choice. The key difference is our leave and attendance module integrates directly with biometric devices, plus we offer unlimited custom reports at no extra cost."},{"question":"Unlimited reports? That is actually something we need.","answer":"Exactly. I can set up a side-by-side comparison demo so you can see the difference yourself. How does Thursday work?"}]'),
('HRMS', 'Customer', 'Post-Demo Follow Up', 5, 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=400&h=250&fit=crop', '[{"question":"Hi! Just following up on the demo from last week. Did you get a chance to discuss it with your team?","answer":"Yes, the team liked it. But we have a few concerns about data migration."},{"question":"Totally valid. We handle the entire migration for you – it is included in the setup. We have migrated companies with 5000+ employees without any downtime.","answer":"That is reassuring. What about the contract – is there a lock-in period?"},{"question":"No lock-in at all. You can go month-to-month or save 20% with an annual plan. Which would you prefer?","answer":"Let us start with annual. Can you send the agreement?"}]');
