// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfjovuwzxyorxkepgiwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmam92dXd6eHlvcnhrZXBnaXdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUzNjMzODYsImV4cCI6MjA5MDkzOTM4Nn0.d6sPLrmXsYF4kK64MKev7fnCHmZ8cWbI33aboTKrjB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});